### ISSUE TITLE
issue with different architectures on terraform validate

### ISSUE THREAD

**Issue by mattbodley** [AleksaC/terraform-py#4]
Hello,

We are having issues where using the tf-validate commit hook sometimes results in issues like:

│ Error while loading schemas for plugin components: Failed to obtain
│ provider schema: Could not load the schema for provider
│ registry.terraform.io/hashicorp/google: failed to instantiate provider
│ "registry.terraform.io/hashicorp/google" to obtain schema: Unrecognized
│ remote plugin message: 
│ Failed to read any lines from plugin's stdout
│ This usually means
│   the plugin was not compiled for this architecture,
│   the plugin is missing dynamic-link libraries necessary to run,
│   the plugin is not executable by this process due to file permissions, or
│   the plugin failed to negotiate the initial go-plugin protocol handshake
│ 
│ Additional notes about plugin:
│   Path: .terraform/providers/registry.terraform.io/hashicorp/google/6.12.0/darwin_arm64/terraform-provider-google_v6.12.0_x5
│   Mode: -rwxr-xr-x
│   Owner: 501 [mattbodley] (current: 501 [mattbodley])
│   Group: 20 [staff] (current: 20 [staff])
│   MachO architecture: CpuArm64 (current architecture: arm64)
│ ..
╵

We think it is because we are running the actual terraform commands in a docker container on a Mac, whereas git is running in the host, so the architectures are different.

However, we have used "terraform providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_amd64"

In order to put all the hash codes in the lock file and it still comes up with this sometimes. Is there a way to simulate this in the command line? 

We were expecting to just work, because since the lock file has all architectures, it _should_ just download the ones it needs and use them regardless of which OS it is currently running on. 

Have you seen this kind of issue before?

**Comment by AleksaC** [comment]
Could you provide more details:

- What version of terraform are you using? 
- On what CPU architecture are you running the command? 
- What is the version of terraform terraform-py downloads?
You can get it by temprorarily modifying the `.pre-commit-config.yaml` to contain the following lines and running `pre-commit run tf-validate --all-files`:
```yaml
      - id: tf-validate
        entry: sh -c "terraform version && exit 1"
```
- Does the issue happen with other providers or different versions of google provider?
- Does the issue occur with system installation of the same version of terraform?

---

> │ Path: .terraform/providers/registry.terraform.io/hashicorp/google/6.12.0/darwin_arm64/terraform-provider-google_v6.12.0_x5
...
> │ MachO architecture: CpuArm64 (current architecture: arm64)

Based on this it seems that terraform is downloading the arm64 build, were you expecting an amd64 one?

---

Note that terraform-py just tries to download the right version of terraform for the given OS and CPU architecture. It is terraform that decides which provider binaries to download.

**Comment by mattbodley** [comment]
Hi AlesksaC 

I have checked it out via running entry: sh -c "terraform version && exit 1" and I get:

Terraform v1.9.8
on darwin_arm64

So I'm guessing this must be the host version that terraform-py downloads, whereas on the Docker image I am running 

Terraform v1.2.9
on linux_amd64

Is there a way to set the version of terraform that terraform-py downloads? 

It seems to work with other providers too, I think it is a general problem accross all of the providers.

When I use the system install version (in the Docker container) it seems to work fine, but then when I use the host system (MacOS) it will create the problem (with the different version above probably not helping).

But also on the Docker image I normally run "terragrunt run-all providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_amd64" which is the same as "terraform providers lock etc" in each directory. 

This will download the lock data for those platforms, whereas I think the terraform-py will not do this, it will probably just get the same platform as the host, right? Therefore the lock files will  be different...

Is there a way to add some commands to the running of the hook so that I can specify which version of terraform e.g. in this case 1.2.9 and also specify which additional lock architectures to also update the providers file?

I think that would probably work as then the versions will be the same and the comparisons will be the  same for the lock hashes

Does that provide all the info you need?

**Comment by AleksaC** [comment]
Thanks for the additional info @mattbodley!

I will try to reproduce this once I find the time, and will get back to you with my findings.

> Is there a way to set the version of terraform that terraform-py downloads?

The terraform version is determined by `rev` field in the pre-commit config. You can specify any version you find in [tags](https://github.com/AleksaC/terraform-py/tags) of this repo:

```yaml
repos:
  - repo: https://github.com/AleksaC/terraform-py
    rev: v1.2.9
    hooks:
      - id: tf-fmt
      - id: tf-validate
```

This specific version fails to build for me, as the SHAs differ between the mirrored version and the one on https://releases.hashicorp.com. It seems that only the SHAs for the MacOS builds have changed, which indicates that they were changed after the fact. Either way, version `1.2.9` Is over two years old at this point, you should consider upgrading if it's possible.

>  normally run "terragrunt run-all providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_amd64"

You are missing `-platform=darwin_arm64` which is the platform it's failing on. 

> This will download the lock data for those platforms, whereas I think the terraform-py will not do this, it will probably just get the same platform as the host, right? Therefore the lock files will be different...

Terraform **should** use the providers for the host platform it's running on. Those should be included in the lockfile, which should be versioned in git. Even if they are missing, `terraform init`, which is ran before `terraform validate` in this hook, should be able to find them and update the lockfile.

While it's possible that `terraform-py` does something that prevents terraform from doing this properly, it seems like it's terraform that's failing here.

**Comment by mattbodley** [comment]
yep thanks for the feedback I have added that extra platform and upgraded terraform to 1.9.8 so hopefully that solves the issue

**Comment by nikaro** [comment]
FTR: I had the same issue, running on a Apple Silicon, but also executing pre-commit hooks in GitHub Actions. But i don't use Terragrunt. To fix this it i had to run this locally: `terraform providers lock -platform=linux_amd64`. It added the missing hashes to the lockfile.

**Comment by mattbodley** [comment]
yep I have done that too I think that helped, as well I have bumped up the version to terraform 1.9.8 which probably made a difference too, although not sure where to go from here whether to go the opentofu route or the terraform route, the terraform upgrade continuation will probably mean no more usage of terragrunt, so would need to remove it, it is great for making the code DRY and more modular and independent and terraform doesn't seem to have any plan for the same kind of features added

**Comment by nikaro** [comment]
@AleksaC do you think it would be possible to add hook doing something like:
```yaml
- id: tf-providers-lock
  name: terraform providers lock
  description: Run terraform providers lock
  entry: terraform-py providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_arm64 -platform=darwin_amd64
  pass_filenames: false
  require_serial: true
  language: python
  types: [terraform]
```

**Comment by nikaro** [comment]
As a workaround i implemented a `tf-providers-lock` hook that if placed before the `tf-validate` one would prevent to commit `.terraform.lock.hcl` with missing hashes.

It works fin on my repo, with:
```yaml
  - repo: https://github.com/nikaro/terraform-py
    rev: 980580b9be183f277a47b3f3b3c5e5a713fe0222
    hooks:
      - id: tf-providers-lock
      - id: tf-fmt
      - id: tf-validate
        exclude: ^modules/
```

If the Terraform code is not at the root of the repo, one would have to pass the correct directory into the args:
```yaml
  - repo: https://github.com/nikaro/terraform-py
    rev: 980580b9be183f277a47b3f3b3c5e5a713fe0222
    hooks:
      - id: tf-providers-lock
        name: Generate lockfile for ./terraform/ directory
        args:
          - --platform=linux_arm64
          - --platform=linux_amd64
          - --platform=darwin_amd64
          - --platform=darwin_arm64
          - ./terraform/
```
